name: Cat Contribution

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: irti-11
          outputs: |
            dist/cat.svg?color_snake=#9d4edd&color_dots=#1a0030,#2d0060,#7b2fff,#b06cff,#ffffff&cat=true
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
