Pac-Man GitHub Action

name: Generate Pac-Man

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate pacman
        uses: hugoalh/github-actions-core@v8.0.0
        continue-on-error: true

      - name: generate pac-man contribution grid
        uses: Sch39/pacman-contribution-grid@v1
        with:
          github-user-name: irtiza001690
          outputs: |
            animation: dist/pacman.svg
            animation_dark: dist/pacman-dark.svg

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
