name: Update GitHub Status Panel

on:
  schedule:
    # Har 6 ghante baad automatically chalega
    - cron: "0 */6 * * *"

  # Button dabane par manually run karne ke liye
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-panel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python script
        run: python generate_status_panel.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add status_panel.svg
          git commit -m "✨ Auto-update animated status panel" || echo "No changes to commit"
          git push
